columns:
  categorical:
    - Vocab_range
    - L1
    - Domain_of_specialization
    - Reading_frequency
    - Other_language

  binary:
    - Reinforced_section

  numerical:
    - Years_studying_L2
    - Stay_duration_weeks
    - Stay_frequency
    - Language_exposure

  label:
    - CEFR_level
