Comparison.Concession: 1
Contingency.Cause: 2
Comparison.Contrast: 3
Expansion.Conjunction: 4
Temporal.Asynchronous: 5
Expansion.Restatement: 6
Expansion: 7
Expansion.Instantiation: 8
EntRel: 9
Expansion.Alternative: 10
Contingency.Condition: 11
Temporal.Synchrony: 12
