linear:
  MLP:
    lr:
      - 0.005
      - 0.001
      - 0.0005

    n_epochs:
      - 100
      - 200
      - 300
      - 500

    hidden_size:
      - 128
      - 192
      - 256
      - 384
      - 512

    weight_decay:
      - 0.005
      - 0.001
      - 0.0005

    batch_size:
      - 32
      - 64
      - 128

    activation:
      - relu
      - leaky_relu

    dropout:
      - 0.0
      - 0.2
      - 0.4

  DecisionTree:
    max_depth:
      - 3
      - 5
      - 7
      - 10
      - 15

    min_samples_split:
      - 5
      - 10
      - 20

    min_samples_leaf:
      - 1
      - 2
      - 5

    max_features:
      - null
      - sqrt
      - log2

    criterion:
      - gini
      - entropy

    class_weight:
      - null
      - balanced

  RandomForest:
    n_estimators:
      - 300
      - 500
      - 800

    max_depth:
      - 5
      - 10
      - 20
      - null

    min_samples_split:
      - 5
      - 10

    min_samples_leaf:
      - 1
      - 2

    max_features:
      - sqrt
      - log2

    bootstrap:
      - true

    class_weight:
      - null
      - balanced

  Logreg:
    C:
      - 0.5
      - 1.0
      - 2.0
      - 5.0
      - 10.0

    penalty:
      - l2

    solver:
      - saga

    max_iter:
      - 300
      - 600
      - 1000

    class_weight:
      - null
      - balanced

    fit_intercept:
      - true

    tol:
      - 1e-4
      - 1e-3

graph:
  GCN:
    hidden_size:
      - 128
      # - 256
      # - 512

    lr:
      - 0.01
      # - 0.005
      # - 0.001

    n_epochs:
      - 1
      # - 100
      # - 200

    embed_dim:
      - 16
      - 32

  GAT:
    hidden_size:
      - 128
      # - 256
      # - 512

    lr:
      - 0.01
      # - 0.005
      # - 0.001

    n_epochs:
      - 1
      # - 100
      # - 200

    embed_dim:
      - 16
      - 32
