MLP:
  lr:
    - 0.1
  n_epochs:
    - 50

  hidden_size:
    - 64

  weight_decay:
    - 0.1

DecisionTree:
  max_depth:
    - null
    - 5
    - 10

  min_samples_split:
    - 2

  min_samples_leaf:
    - 1
    - 2

  criterion:
    - gini
    - entropy

RandomForest:
  n_estimators:
    - 100

  max_depth:
    - null
    - 10

  min_samples_split:
    - 2
    - 5

  min_samples_leaf:
    - 1
    - 2

  max_features:
    - sqrt
    - log2
    - null

Logreg:
  C:
    - 0.01
    - 0.1

  penalty:
    - l1
    - l2

  solver:
    - liblinear
    - saga

  max_iter:
    - 100

  class_weight:
    - null
    - balanced
